version: "3.8"

services:
  pdi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PDI_URL: https://github.com/ambientelivre/legacy-pentaho-ce/releases/download/pdi-ce-9.3.0.0-428/pdi-ce-9.3.0.0-428.zip

    container_name: pdi-93
    restart: unless-stopped

    mem_limit: 4g
    cpus: 1.0

    environment:
      - JAVA_OPTS=-Xms512m -Xmx3g
      - KETTLE_HOME=/opt/pdi/config

    volumes:
      - ./config:/opt/pdi/config
      - ./.kettle:/opt/pdi/config/.kettle
      - ./logs:/opt/pdi/logs
      - ./data:/opt/pdi/data

    command: tail -f /dev/null