# Este arquivo foi gerado por Pentaho Data Integration versão 9.4.0.0-343.
#
# Estos são alguns exemplos de criação de variáveis:
#
# SERVIDOR_PROD = hercules
# SERVIDOR_TEST = zeus
# SERVIDOR_DESENV = thor
#
# Nota: linhas como esta com um # no início são comentários
#

#Diretório Padrão
PATH_REPOSITORY=/opt/pdi/Sources

# OLIST PRODUCAO
OLIST_PRD_HOST=vps.scarsi.com.br
OLIST_PRD_DB=postgres_prd
OLIST_PRD_PORT=32769
OLIST_PRD_USER=jeferson_scarsi
OLIST_PRD_PASSWORD=Tcc.123

# OLIST DW
OLIST_DW_HOST=vps.scarsi.com.br
OLIST_DW_DB=tcc_scarsi
OLIST_DW_PORT=32768
OLIST_DW_USER=jeferson_scarsi
OLIST_DW_PASSWORD=Tcc.123
